### ISSUE TITLE
Add a project license

### ISSUE THREAD

**Issue by Calinou** [adamhynek/activeragdoll#1]
The repository currently doesn't seem to contain any license. Could you add one, please? See [Choose a License](https://choosealicense.com/) for more information :slightly_smiling_face:

**Comment by adamhynek** [comment]
I've made it GPL like with my other repos.
Was there a particular reason you were asking, something you're working on? I'm just curious.

**Comment by Calinou** [comment]
Thanks!

> Was there a particular reason you were asking, something you're working on? I'm just curious.

Not specifically, I just saw this project linked in a chat.
